#!/bin/sh
################################################################################
# PX4 SITL Configuration for QuadTailsitter in X-Plane
################################################################################
#
# @name              QuadTailsitter X-Plane SITL
# @class             VTOL
# @type              VTOL Quad Tailsitter
# @maintainer        alireza787b <p30planets@gmail.com>
# @url               https://github.com/alireza787b/px4xplane/
#
# X-Plane model:     QuadTailsitter.acf
# Compatible Sim:    X-Plane 12
# Control:           Four fixed rotors, no aerodynamic control surfaces
#
# This is a hover, low-speed navigation, and first airspeed-gated transition
# configuration. It follows PX4's official quadtailsitter SITL pattern, then
# applies the px4xplane sensor-fusion lessons learned from Alia and Ehang.
# qtail11 confirmed that X-Plane's conventional IAS dataref is negative in
# tailsitter fixed-wing attitude while the px4xplane body-axis pitot projection
# on -Z matches true airspeed. This file therefore enables PX4 airspeed feedback
# for transition and TECS while keeping checks conservative for SITL.
#
# USAGE:
#   make px4_sitl_default xplane_qtailsitter
#
################################################################################

. ${R}etc/init.d/rc.vtol_defaults


################################################################################
# AIRFRAME AND CONTROL ALLOCATION
################################################################################

param set-default MAV_TYPE 20
param set-default CA_AIRFRAME 4
param set-default CA_METHOD 2
param set-default CA_FAILURE_MODE 0

# qtail1 showed that the previous geometry used the X-Plane coordinates
# directly. X-Plane aircraft coordinates use X=right, Y=up, Z=tail; Plane Maker
# ACF position values are in feet. PX4 control allocation needs body X=forward
# and body Y=right in meters. The conversion below is:
#   PX4_X = -XPLANE_Z * 0.3048
#   PX4_Y =  XPLANE_X * 0.3048
# It preserves the existing px4xplane channel order and PX4 quadtailsitter sign
# pattern.
#
# qtail14 showed the aircraft was still the old 5 lb model, not the intended
# 5 kg 6S quad tailsitter. The v3.4.37 ACF retargets mass, battery, motor RPM,
# and a small 5 degree mirrored motor cant. Keep CT/KM conservative for the
# first 5 kg hover test and use the cant axes below to match the ACF.
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.22
param set-default CA_ROTOR0_PY 0.43
param set-default CA_ROTOR0_AX -0.078
param set-default CA_ROTOR0_AY 0.040
param set-default CA_ROTOR0_AZ -0.996
param set-default CA_ROTOR0_CT 2.0
param set-default CA_ROTOR0_KM 0.04

param set-default CA_ROTOR1_PX -0.22
param set-default CA_ROTOR1_PY -0.43
param set-default CA_ROTOR1_AX 0.078
param set-default CA_ROTOR1_AY -0.040
param set-default CA_ROTOR1_AZ -0.996
param set-default CA_ROTOR1_CT 2.0
param set-default CA_ROTOR1_KM 0.04

param set-default CA_ROTOR2_PX 0.22
param set-default CA_ROTOR2_PY -0.43
param set-default CA_ROTOR2_AX -0.078
param set-default CA_ROTOR2_AY -0.040
param set-default CA_ROTOR2_AZ -0.996
param set-default CA_ROTOR2_CT 2.0
param set-default CA_ROTOR2_KM -0.04

param set-default CA_ROTOR3_PX -0.22
param set-default CA_ROTOR3_PY 0.43
param set-default CA_ROTOR3_AX 0.078
param set-default CA_ROTOR3_AY 0.040
param set-default CA_ROTOR3_AZ -0.996
param set-default CA_ROTOR3_CT 2.0
param set-default CA_ROTOR3_KM -0.04

param set-default CA_SV_CS_COUNT 0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104


################################################################################
# PX4XPLANE SENSOR BASELINE
################################################################################

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SYS_HAS_BARO 1
param set-default SYS_HAS_GPS 1

param set-default CAL_BARO0_ID 6620172
param set-default CAL_BARO0_PRIO 100
param set-default CAL_BARO1_ID 6620428
param set-default CAL_BARO1_PRIO 0

param set-default EKF2_BARO_CTRL 1
param set-default EKF2_BARO_NOISE 1.0
param set-default EKF2_BARO_DELAY 0.0
param set-default EKF2_BARO_GATE 10.0
param set-default EKF2_HGT_REF 1

param set-default EKF2_GPS_CTRL 7
param set-default EKF2_GPS_DELAY 0.0
param set-default EKF2_GPS_P_NOISE 0.15
param set-default EKF2_GPS_V_NOISE 0.15
param set-default EKF2_GPS_P_GATE 5.0
param set-default EKF2_GPS_V_GATE 5.0

param set-default EKF2_MAG_TYPE 0
param set-default EKF2_HEAD_NOISE 0.3
param set-default EKF2_MAG_NOISE 0.05
param set-default EKF2_MAG_GATE 5.0
param set-default EKF2_FUSE_BETA 0

param set-default EKF2_ABIAS_INIT 0.2
param set-default EKF2_ABL_LIM 2.5
param set-default EKF2_ABL_TAU 0.5
param set-default EKF2_ABL_ACCLIM 35.0
param set-default EKF2_ACC_NOISE 1.0
param set-default EKF2_ACC_B_NOISE 0.001
param set-default EKF2_GYR_NOISE 0.015
param set-default EKF2_GYR_B_NOISE 0.001
param set-default EKF2_MULTI_IMU 1
param set-default EKF2_AGP_CTRL 3
param set-default EKF2_ASP_DELAY 0.0
param set-default EKF2_AVEL_DELAY 0.0
param set-default EKF2_TAS_GATE 5.0
param set-default EKF2_WIND_NSD 0.01
param set-default EKF2_REQ_VDRIFT 1.0

param set-default IMU_GYRO_RATEMAX 200
param set-default IMU_INTEG_RATE 200


################################################################################
# MULTICOPTER HOVER CONTROL
################################################################################

# Preserve yaw authority at low hover thrust. PX4 requires stick arming to be
# disabled when yaw airmode is enabled.
param set-default MC_AIRMODE 2
param set-default MAN_ARM_GESTURE 0

param set-default MC_ROLL_P 0.9
param set-default MC_PITCH_P 0.9
param set-default MC_YAW_P 0.80
param set-default MC_YAW_WEIGHT 0.35

param set-default MC_ROLLRATE_P 0.10
param set-default MC_ROLLRATE_I 0.02
param set-default MC_ROLLRATE_D 0.0008
param set-default MC_ROLLRATE_FF 0.0
param set-default MC_ROLLRATE_K 1.00
param set-default MC_ROLLRATE_MAX 80

param set-default MC_PITCHRATE_P 0.10
param set-default MC_PITCHRATE_I 0.02
param set-default MC_PITCHRATE_D 0.0008
param set-default MC_PITCHRATE_FF 0.0
param set-default MC_PITCHRATE_K 1.00
param set-default MC_PITCHRATE_MAX 80

param set-default MC_YAWRATE_P 0.20
param set-default MC_YAWRATE_I 0.015
param set-default MC_YAWRATE_D 0.025
param set-default MC_YAWRATE_FF 0.0
param set-default MC_YAWRATE_K 1.20
param set-default MC_YAWRATE_MAX 65


################################################################################
# MULTICOPTER POSITION, TAKEOFF, AND LANDING
################################################################################

param set-default MPC_XY_P 0.18
param set-default MPC_Z_P 1.00
param set-default MPC_XY_VEL_P_ACC 0.8
param set-default MPC_XY_VEL_I_ACC 0.1
param set-default MPC_XY_VEL_D_ACC 0.2
param set-default MPC_Z_VEL_P_ACC 2.0
param set-default MPC_Z_VEL_I_ACC 0.5
param set-default MPC_Z_VEL_D_ACC 0.5

param set-default MPC_XY_VEL_MAX 5.0
param set-default MPC_XY_CRUISE 5.0
param set-default MPC_VEL_MANUAL 5.0
param set-default MPC_Z_V_AUTO_UP 1.0
param set-default MPC_Z_V_AUTO_DN 1.4
param set-default MPC_Z_VEL_MAX_UP 1.2
param set-default MPC_Z_VEL_MAX_DN 1.4
param set-default MPC_XY_ERR_MAX 10

param set-default MPC_ACC_HOR 1.2
param set-default MPC_ACC_HOR_MAX 1.8
param set-default MPC_ACC_UP_MAX 1.6
param set-default MPC_ACC_DOWN_MAX 1.5
param set-default MPC_JERK_AUTO 1.2
param set-default MPC_JERK_MAX 2.0

param set-default MPC_MAN_TILT_MAX 35
param set-default MPC_TILTMAX_AIR 40
param set-default MPC_TILTMAX_LND 8

param set-default MPC_THR_HOVER 0.30
param set-default MPC_THR_MIN 0.08
param set-default MPC_THR_MAX 1.0
param set-default MPC_THR_XY_MARG 0.3
param set-default MPC_USE_HTE 0

param set-default MPC_TKO_SPEED 1.0
param set-default MPC_TKO_RAMP_T 2.5
param set-default MIS_TAKEOFF_ALT 1.5
param set-default MPC_LAND_ALT1 8
param set-default MPC_LAND_ALT2 3
param set-default MPC_LAND_ALT3 1
param set-default MPC_LAND_SPEED 0.9
param set-default MPC_LAND_CRWL 0.36
param set-default MPC_LAND_RADIUS 30

param set-default LNDMC_ALT_GND 1.5
param set-default LNDMC_XY_VEL_MAX 1.5
param set-default LNDMC_Z_VEL_MAX 0.30
param set-default LNDMC_ROT_MAX 25
param set-default LNDMC_TRIG_TIME 1
param set-default COM_DISARM_LAND 1.5

param set-default MPC_YAW_MODE 0
param set-default MPC_YAWRAUTO_ACC 12
param set-default MPC_YAWRAUTO_MAX 35
param set-default MIS_YAW_ERR 30
param set-default MIS_YAW_TMT 5
param set-default MC_ORBIT_YAW_MOD 1


################################################################################
# FIXED-WING ENVELOPE AND ENERGY CONTROL
################################################################################

# qtail11-qtail14 truth showed that px4xplane body-axis pitot (-Z) is positive
# and close to X-Plane true airspeed in FW mode. Use it for transition gating
# and TECS. Do not make the virtual SITL pitot a prearm hardware requirement:
# commander can run before the simulator stream and airspeed_selector warm up.
param set-default FW_USE_AIRSPD 1
param set-default ASPD_DO_CHECKS 1
param set-default ASPD_FALLBACK 1
param set-default SYS_HAS_NUM_ASPD 0

param set-default FW_AIRSPD_STALL 16
param set-default FW_AIRSPD_MIN 21
param set-default FW_AIRSPD_TRIM 28
param set-default FW_AIRSPD_MAX 40

param set-default FW_THR_TRIM 0.16
param set-default FW_THR_MAX 0.40
param set-default FW_THR_MIN 0.00
param set-default FW_THR_IDLE 0.00
param set-default FW_THR_SLEW_MAX 0.20

param set-default FW_T_CLMB_MAX 5
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 1.6
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_ALT_TC 5.0
param set-default FW_T_SPDWEIGHT 1.5
param set-default FW_T_RLL2THR 2.0
param set-default FW_T_STE_R_TC 1.0
param set-default FW_T_THR_DAMPING 0.25
param set-default FW_T_PTCH_DAMP 0.25
param set-default FW_T_I_GAIN_PIT 0.25

param set-default FW_P_TC 0.6
param set-default FW_PSP_OFF 4.0
param set-default FW_P_LIM_MAX 35
param set-default FW_P_LIM_MIN -15
param set-default FW_PR_P 0.50
param set-default FW_PR_I 0.30
param set-default FW_PR_D 0.0

param set-default FW_R_TC 0.6
param set-default FW_R_LIM 28
param set-default FW_RR_P 0.20
param set-default FW_RR_I 0.10
param set-default FW_RR_D 0.0
param set-default FW_RR_FF 0.10

param set-default FW_YR_P 0.10
param set-default FW_YR_I 0.0
param set-default FW_YR_D 0.0
param set-default FW_YR_FF 0.0


################################################################################
# VTOL TRANSITION
################################################################################

param set-default VT_TYPE 0
param set-default VT_ARSP_BLEND 18
param set-default VT_ARSP_TRANS 24
param set-default VT_F_TRANS_DUR 8.0
param set-default VT_F_TRANS_THR 0.55
param set-default VT_F_TR_OL_TM 12.0
param set-default VT_TRANS_MIN_TM 6.0
param set-default VT_TRANS_TIMEOUT 30
param set-default VT_B_TRANS_DUR 8.0
param set-default VT_B_DEC_MSS 1.2
param set-default VT_B_DEC_I 0.1
param set-default VT_B_TRANS_RAMP 6.0
param set-default VT_FW_MIN_ALT 30
param set-default VT_QC_T_ALT_LOSS 35
param set-default VT_PITCH_MIN -10
param set-default VT_FWD_THRUST_EN 0

param set-default VT_FW_DIFTHR_EN 7
param set-default VT_FW_DIFTHR_S_R 1.0
param set-default VT_FW_DIFTHR_S_P 1.0
param set-default VT_FW_DIFTHR_S_Y 1.0


################################################################################
# NAVIGATION AND FAILSAFE
################################################################################

param set-default NPFG_PERIOD 34.0
param set-default NPFG_DAMPING 1.00
param set-default NPFG_ROLL_TC 1.5
param set-default NAV_ACC_RAD 12
param set-default NAV_MC_ALT_RAD 2
param set-default NAV_LOITER_RAD 900
param set-default RTL_LOITER_RAD 900
param set-default RTL_RETURN_ALT 100
param set-default RTL_DESCEND_ALT 75
param set-default RTL_MIN_DIST 50

param set-default FD_FAIL_R 70
param set-default WV_EN 0

################################################################################
# END OF FILE
################################################################################
